---
resources:
  - name: hula
    type: git
    source:
      uri: https://github.com/pivotal-cf-experimental/hula
      branch: master

jobs:
  - name: tests
    plan:
    - get: hula
      trigger: true
    - task: run-tests
      file: hula/ci/run-tests.yml
